version: "3.8"
services:
  proxy:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      - POSTGRES_USER=proxyuser
      - POSTGRES_PASSWORD=proxypass
      - POSTGRES_DB=proxydb
      - DB_HOST=postgres
      - DB_PORT=5432
    volumes:
      - ./ca_cert.pem:/app/ca_cert.pem
      - ./ca_key.pem:/app/ca_key.pem
      - ./dicc.txt:/app/dicc.txt
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=proxyuser
      - POSTGRES_PASSWORD=proxypass
      - POSTGRES_DB=proxydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: